### ISSUE TITLE
Discord Link invalid

### ISSUE THREAD

**Issue by filipkujawa** [ywppp/fsnipe#1]
The discord link is invalid, just wanted to let you know :)

**Comment by filipkujawa** [comment]
Also i cant find the exe file

**Comment by ywppp** [comment]
hey, i created this back in june when i wanted to make my bot open source, but i'm no longer active in both the community and sniping in general.

in terms of the exe file - i don't think i created it properly, so use the python file and parse through the code to understand how i created it, let me know if there are any questions :)

discord: https://discord.gg/sniper (poseidon sniping community)
discord personal: ywp#8011
